# Generated by Django 5.2 on 2025-04-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinghistory',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-reviewed_at']},
        ),
        migrations.RenameField(
            model_name='bookinghistory',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='bookinghistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='showtime_id',
            new_name='showtime',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='auditorium_id',
            new_name='auditorium',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
