# Generated by Django 5.2 on 2025-04-12 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_bookinghistory_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoriums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('showtime', 'seat_number')},
        ),
    ]
