# Generated by Django 5.2 on 2025-04-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auditorium_admin_alter_seat_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinghistory',
            old_name='showtime_id',
            new_name='showtime',
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='total_shows',
            field=models.PositiveIntegerField(),
        ),
    ]
