# Generated by Django 5.1.7 on 2025-04-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_showtime_id_bookinghistory_showtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.seat'),
        ),
    ]
