# Generated by Django 5.2 on 2025-04-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='user_id',
            new_name='user',
        ),
    ]
